---
train:
  params:
    batch_size: 256
    epoch: 12
    lr: 0.001
    decay: 0.1
    decay_step:
      - 8
  save:
    save_path: "./ResNet18"
    model_name: "ResNet18"
    step: 1
  data:
    image: '/disk1/repository/isGazeOnPhone/new_data/output/image'
    label: '/disk1/repository/isGazeOnPhone/new_data/output/label/train'
  pretrains: "None"
test:
   load:
      begin_step: 11
      end_step: 12
      steps: 1
      model_name: "ResNet18"
      load_path: "./ResNet18"
   data:
    image: '/disk1/repository/isGazeOnPhone/new_data/output/image'
    label: '/disk1/repository/isGazeOnPhone/new_data/output/label/test'
reader: reader
